rails-app-challenge/config/routes.rb
Rails.application.routes.draw do
  resources :properties, only: %i[index new show create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "properties#index"
end

rails-app-challenge/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails-app-challenge/app/models/property.rb
class Property < ApplicationRecord
  has_many_attached :images
end

rails-app-challenge/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

rails-app-challenge/app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show ]

  # GET /properties or /properties.json
  def index
    @pagy, @properties = pagy(Property.all, items: 8)

    respond_to do |format|
      format.html
      format.json {
        render json: { properties: render_to_string(partial: 'properties/partials/properties', formats: [:html]), pagination: view_context.pagy_next_link(@pagy) }
      }
    end
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to property_url(@property), notice: "Property was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:district, :street, :bedrooms, :bathrooms, :availability, :price, images: [])
    end
end

rails-app-challenge/app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

rails-app-challenge/app/helpers/properties_helper.rb
module PropertiesHelper
end

rails-app-challenge/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAppChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="mob-modal" class="d-none">
      <%= render partial: 'shared/navigation/moblinks' %>
    </div>
    <%= render partial: 'shared/navigation/navbar' %>
    <main class="main-container">
      <%= yield %>
    </main>
  </body>
</html>

rails-app-challenge/app/views/properties/index.html.erb
<p style="color: green"><%= notice %></p>

<div data-controller="increment-pagination">
  <div class="properties-container"
       id="properties"
       data-increment-pagination-target="properties">
      <%= render partial: 'properties/partials/properties' %>
  </div>

  <div class="load-more-container"> 
    <div class="load-more-items-container">
      <div>
        <p class="load-more-p">Showing <span class="load-more-p" data-increment-pagination-target="counter">8</span> of <span class="load-more-p" data-increment-pagination-target="total"><%= Property.count %> properties</span></p>
      </div>
      <div class="counter-bar-container">
        <span class="full-counter-bar">
          <span class="progress-counter-bar"
                data-increment-pagination-target="progressBar"
                data-action="load@window->increment-pagination#updateCounterProgress"></span>
        </span>
      </div>
      <div class="load-more-btn-wrapper">
        <button class='load-more-btn' data-action="click->increment-pagination#loadMore">
          Load more
        </button>
      </div>
      <div class="load-more-btn-wrapper d-none" data-increment-pagination-target="pagination"
        >
        <%== pagy_next_link(@pagy, text: 'Load more', link_extra: 'style="display: none;"') %>
      </div>
    </div>
  </div>

<div>

rails-app-challenge/app/views/properties/new.html.erb
<h1>New property</h1>

<%= render partial: "properties/partials/form", locals: { property: @property } %>

<br>

rails-app-challenge/app/views/properties/partials/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :district, style: "display: block" %>
    <%= form.text_field :district %>
  </div>

  <div>
    <%= form.label :street, style: "display: block" %>
    <%= form.text_field :street %>
  </div>

  <div>
    <%= form.label :bedrooms, style: "display: block" %>
    <%= form.number_field :bedrooms %>
  </div>

  <div>
    <%= form.label :bathrooms, style: "display: block" %>
    <%= form.number_field :bathrooms %>
  </div>

  <div>
    <%= form.label :availability, style: "display: block" %>
    <%= form.date_field :availability %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :images, style: "display: block" %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

rails-app-challenge/app/views/properties/partials/_properties.html.erb
<% @properties.each do |property| %>
  <%= render partial: 'properties/partials/property', locals: { property: property } %>
<% end %>

rails-app-challenge/app/views/properties/partials/_property.html.erb
<div class="property-container" >
  <a class="property-link" href="<%= property_path(property.id)%>">
    <div class="property-data-container">
      <div class="slide-show-container">
        <%= image_tag property.images[3], class: "property-img" %>
      </div>
      <div class="property-info-container">
        <div>
          <span class="property-info-title3"><%= property.district %></span>
          <h3 class="property-info-title1"><%= property.street %></h3>
          <span class="property-info-title4"><%= property.bedrooms %> bedroom • <%= property.bathrooms %> bath</span>
        </div>
        <div class="property-price-container">
          <div class="price-wrapper">
            <span class="property-info-title3 line-through">R$<%= property.price %></span>
            <h4 class="property-info-title2">
              R$<%= (property.price * 0.9699).round() %>
              <span class="property-info-title4">/mo</span>
            </h4>
          </div>
          <div>
            <div class="property-availability-wrapper">
              <span class="property-info-title4">Available</span>
              <span class="property-info-title5"><%= Date.parse(property.availability.to_s).strftime('%d %b') %></span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </a>
</div>

rails-app-challenge/app/views/properties/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render partial: 'properties/partials/property', locals: { property: @property } %>

<div>
  <%= link_to "Back to properties", properties_path %>
</div>

rails-app-challenge/app/views/shared/navigation/_moblinks.html.erb
<div class="p-absolute mob-menu-container" data-controller="navigation-bar">
  <div class="p-relative mob-menu-items-container">
    <%# logo container %>
    <h2 class="d-flex mob-menu-header-2">
      <div class="d-flex w-100 justify-center">
        <%= image_tag 'logos/logo-dark.svg', class: 'logo' %>
      </div>
      <div class="d-flex align-center c-pointer" data-action="click->navigation-bar#closeMenu">
        <%= image_tag 'icons/close-icon.svg' %>
      </div>
    </h2>
    <%# Div dentro de div com scroll %>
    <div class="mob-links-container">
      <%# Div com M-top 2rem %>
      <div class="mob-link-items-container">
        <%# Links %>
        <ul>
          <li>
            <a class="nav-links-style mob-links-items-a" href="/" >
              APARTMENTS
            </a>
            <hr>
          </li>
          <li>
            <a class="nav-links-style mob-links-items-a" href="/properties/new">
              ADD APARTMENT
            </a>
            <hr>
          </li>
        </ul>
        <%# Contact %>
        <p class="mob-link-items-p">Contact Us</p>
        <ul>
          <li>
            <div class="d-flex"> 
              <%= image_tag 'icons/whatsapp.svg', class: 'mob-links-contact-icon' %>
              <a class="nav-links-style mob-links-items-a" href="/">
                +55 31900000000
              </a>            
            </div>

            <hr>
          </li>
          <li>
            <div class="d-flex"> 
              <%= image_tag 'icons/phone.svg', class: 'mob-links-contact-icon' %>
              <a class="nav-links-style mob-links-items-a" href="/">
                +55 31900000000
              </a>            
            </div>
            <hr>
          </li>
          <li>
            <div class="d-flex"> 
              <%= image_tag 'icons/envelope.svg', class: 'mob-links-contact-icon' %>
              <a class="nav-links-style mob-links-items-a" href="/">
                foo@foo.com
              </a>           
            </div>
            <hr>
          </li>
        </ul>
        <%# Language %>
        <p class="mob-link-items-p">Language</p>
        <ul>
          <li>
            <div class="d-flex justify-between">
              <div class="d-flex">
                <%= image_tag 'icons/globe.svg', class: 'mob-links-contact-icon' %>
                <a class="nav-links-style mob-links-items-a" href="/">
                  English
                </a>
              </div>
              <%= image_tag 'icons/mini-arrow-right.svg' %>
            </div>
            <hr>          
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

rails-app-challenge/app/views/shared/navigation/_navbar.html.erb
<div class="navbar-container">
  <header data-controller="navigation-bar"
          class="d-flex align-center justify-between">
    <section data-navigation-bar-target="headersection"
             class="d-flex align-center w-100">
      
      <% if request.path == '/' || request.path == '/properties' %>
        <a href="/"
         class="d-flex align-center logo-cropped"
         data-navigation-bar-target="headerLogo"
         data-action="load->navigation-bar#toggleCropImage load@window->navigation-bar#toggleCropImage resize@window->navigation-bar#toggleCropImage">
          <%= image_tag 'logos/logo-dark.svg',
              class: "logo" %>
        </a>
      <% else %>
        <a href="/"
         class="d-flex align-center"
         data-navigation-bar-target="headerLogo" >
          <%= image_tag 'logos/logo-dark.svg',
              class: "logo" %>
        </a>
      <% end %>
        

      <div id="location-container"
           class="d-flex location-container justify-center align-center"
          >
          <% if request.path == '/' || request.path == '/properties' %>
            <h4 class="location-header"
                data-navigation-bar-target="locationHeader" >
                  Explore • São Paulo
            </h4>
          <% end %>
          <%= image_tag 'icons/arrow-down.svg',
                        class: 'd-none',
                        "data-navigation-bar-target": "locationIcon" %>
      </div>
      <%# This section is hidden in mobile view %>
      <nav id="links-container" class="desk-only-flex d-none d-flex align-center">
        <div class="d-flex align-center justify-center globe-container">
          <%= image_tag 'icons/globe.svg', class: 'globe-icon' %>
        </div>
        <div class="d-flex align-center ml-links">
          <a href="/properties" class="nav-links-style">
            APARTMENTS
          </a>
        </div>
        <div class="d-flex align-center ml-links">
          <a href="/properties/new" class="nav-links-style">
            ADD APARTMENT
          </a>
        </div>
      </nav>
    </section>
    <%# Another controller should handle the toggle/untoggle of the modal options %>
    <div class="ham-menu-container"
         data-navigation-bar-target="hamBtnCon"
         >
        <button class="ham-menu-btn d-flex align-center justify-center" data-action="click->navigation-bar#showMenu">
          <%= image_tag 'icons/hamburguer_menu.svg' %>
        </button>
    </div>
  </header>
</div>